### ISSUE TITLE
Cannot pull data from Google Sheets

### ISSUE THREAD

**Issue by ardiishere** [biolab/orange3-educational#144] opened 2022-03-21 07:45 UTC
**What's wrong?**
I cannot pull data from Google Sheet. I have open the access but, still unable to pull data.
The error message is: Couldn't load spreadsheet!
 ![Google Sheets](https://user-images.githubusercontent.com/75511812/159220311-ad2f9476-8d21-471a-b1b9-725370b6a591.png)

**How can we reproduce the problem?** 
1. Open new blank file.
2. Choose Educational --> Google Sheet
3. Paste your long Google Sheet address into dialog box in Orange
4. Error message will appear

**I find workaround by doing these** 
1. Open new blank file.
2. Choose Educational --> Google Sheet
3. Copy your Google Sheet address to URL Shortener services like Bitly
4. Paste your bitly link into Orange dialog box
5. Data will be pulled like usual
![Google Sheets 2](https://user-images.githubusercontent.com/75511812/159221251-fc0b7604-3513-4646-b7e9-1438de3b208b.png)

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.31.1
- How you installed Orange: Download from https://orangedatamining.com/download/#windows

**Comment by ajdapretnar** [comment] 2022-03-21 07:53
The widget should be updated as: https://github.com/biolab/orange3/pull/5788

**Comment by ardiishere** [comment] 2022-03-22 04:31
How do I update it?
Should I expect the newer version?

**Comment by ajdapretnar** [comment] 2022-03-22 08:15
It is not yet done, this was just a note to the developers, sorry. Once the fix is ready and merged, it will be shown in the thread below. Then a new version of Educational add-on will be issues and you will be able to update.

**Comment by ardiishere** [comment] 2022-03-22 15:20
Ah. I see. Thanks you for the clarification!
Semangat!

You guys are awesome!

**Comment by ajdapretnar** [comment] 2022-03-25 10:44
To be honest, I cannot reproduce this error anymore. Do you perhaps still have a sample Google Sheet which fails in the widget?

**Comment by janezd** [comment] 2022-05-07 10:00
Works for me, too.

**Closed by janezd** 2022-05-07 10:00 UTC
Labels: bug report
